import React from "react";

import "./ExpenseFilter.css";

const ExpensesFilter = (props) => {
  //controll component
  // when the input or props are the intiall state or value of component
  // and the output or data generated by the compnonet are also used by parent
  // then it is control component (all things are handle by parent)
  const handleChange = (event) => {
    props.changeYear(event.target.value);
  };
  return (
    <div className="expenses-filter">
      <div className="expenses-filter__control">
        <label>Filter by year</label>
        <select value={props.year} onChange={handleChange}>
          <option value="2022">2022</option>
          <option value="2021">2021</option>
          <option value="2020">2020</option>
          <option value="2019">2019</option>
        </select>
      </div>
    </div>
  );
};
export default ExpensesFilter;
